-- to create a new table just run this in hive:
CREATE EXTERNAL TABLE lakehouse_pocs.delta_exp2_history (
    event_id STRING,
    source STRING,
    version STRING,
    uuid STRING,
    last_updated_timestamp BIGINT,
    dashboardLoaded BOOLEAN,
    webDataFlowTimeStamp INT,
    mobileDataFlowTimeStamp INT,
    locality STRING,
    city STRING,
    state STRING,
    timezone STRING,
    zip STRING,
    country STRING,
    regionCode STRING,
    ratesSchedule STRING,
    addressType STRING,
    partnerUserHomeId STRING,
    livingArea DOUBLE,
    lastProfileTime INT,
    meterId STRING,
    defNTypeId INT,
    defNhoodId INT,
    nhood STRING,
    supplementaryNhoodIds STRING,
    utilityUserName STRING,
    lseId STRING,
    billstart INT,
    lastRawDataArchivedTS INT,
    dwelling INT,
    yearBuilt INT,
    numberOfAdults INT,
    solarUser BOOLEAN,
    adrUser BOOLEAN,
    showDevicePairing BOOLEAN,
    numberOfChildren INT,
    enrollmentTime INT,
    lotSize DOUBLE,
    bathrooms DOUBLE,
    bedrooms INT,
    floors INT,
    totalRooms INT,
    occupantType STRING,
    numOccupants INT,
    ownershipType STRING,
    spaceHeatingType STRING,
    waterHeatingType STRING,
    qualifiedForSurvey BOOLEAN,
    sentSurvey1 BOOLEAN,
    sentMissingOutHan BOOLEAN,
    sentMissingData BOOLEAN,
    sentSurvey2 BOOLEAN,
    sentSurvey3 BOOLEAN,
    serial STRING,
    thermostats STRING,
    lastMonthBill DOUBLE,
    lastMonthKwh DOUBLE,
    firstDataProcessTime INT,
    plannumber INT,
    utilityunknown STRING,
    utilityName STRING,
    planunknown STRING,
    ratePlanId STRING,
    billCycleCode STRING,
    rateType STRING,
    defaultRate DOUBLE,
    rateQuery STRING,
    masterTariffId STRING,
    emailsBlocked BOOLEAN,
    notificationsBlocked BOOLEAN,
    dailyTierChangeAlertList STRING,
    weeklySummaryList STRING,
    monthlySummaryList STRING,
    disconnectsSentPerWeek STRING,
    dailyTierChangeAlert BOOLEAN,
    dailyUsageUpAlert BOOLEAN,
    dailyUsageDownAlert BOOLEAN,
    dailyPeakToUUsageUpAlert BOOLEAN,
    dailyUsageUpAlertList STRING,
    dailyUsageUpAlertPercent DOUBLE,
    dailyUsageDownAlertList STRING,
    dailyUsageDownAlertPercent DOUBLE,
    dailyPeakToUUsageUpAlertPercent DOUBLE,
    dailyPeakToUUsageUpAlertList STRING,
    notifyEmailStatusChange BOOLEAN,
    notifyEmailState STRING,
    notifyEmailGBState STRING,
    notifyEmailWeeklyStatus BOOLEAN,
    notifyEmailMonthlyStatus BOOLEAN,
    firstTimeHanConnectEmailed BOOLEAN,
    firstTimeGBConnectEmailed BOOLEAN,
    firstTimeGBConnectNotified BOOLEAN,
    blackList STRING,
    releaseList STRING,
    nsp STRING,
    nst STRING,
    checkedDILSO BOOLEAN,
    latitude DOUBLE,
    longitude DOUBLE,
    budgetThresholdAmount DOUBLE,
    s3FileDumpState STRING,
    lastStreamedBillProjection INT,
    businessName STRING,
    userSegment STRING,
    userBusinessType STRING,
    partnerProvidedUserBusinessType STRING,
    userBusinessSubType STRING,
    businessTimings STRING,
    smartBudgetEnabled BOOLEAN,
    businessCode STRING,
    addressMatchingThirdPartyData BOOLEAN,
    billingSchedule STRING,
    status STRING,
    crud_op STRING,
    event_date DATE
)
PARTITIONED BY (pilot_id STRING)
STORED AS PARQUET
LOCATION 's3://bidgely-lakehouse-pocs/experiments/experiment2/deltalake/_history/';


-- and then this
MSCK REPAIR TABLE lakehouse_pocs.delta_exp2_history;




CREATE EXTERNAL TABLE lakehouse_pocs.hudi_exp2_history (
    event_id STRING,
    source STRING,
    version STRING,
    uuid STRING,
    last_updated_timestamp BIGINT,
    dashboardLoaded BOOLEAN,
    webDataFlowTimeStamp INT,
    mobileDataFlowTimeStamp INT,
    locality STRING,
    city STRING,
    state STRING,
    timezone STRING,
    zip STRING,
    country STRING,
    regionCode STRING,
    ratesSchedule STRING,
    addressType STRING,
    partnerUserHomeId STRING,
    livingArea DOUBLE,
    lastProfileTime INT,
    meterId STRING,
    defNTypeId INT,
    defNhoodId INT,
    nhood STRING,
    supplementaryNhoodIds STRING,
    utilityUserName STRING,
    lseId STRING,
    billstart INT,
    lastRawDataArchivedTS INT,
    dwelling INT,
    yearBuilt INT,
    numberOfAdults INT,
    solarUser BOOLEAN,
    adrUser BOOLEAN,
    showDevicePairing BOOLEAN,
    numberOfChildren INT,
    enrollmentTime INT,
    lotSize DOUBLE,
    bathrooms DOUBLE,
    bedrooms INT,
    floors INT,
    totalRooms INT,
    occupantType STRING,
    numOccupants INT,
    ownershipType STRING,
    spaceHeatingType STRING,
    waterHeatingType STRING,
    qualifiedForSurvey BOOLEAN,
    sentSurvey1 BOOLEAN,
    sentMissingOutHan BOOLEAN,
    sentMissingData BOOLEAN,
    sentSurvey2 BOOLEAN,
    sentSurvey3 BOOLEAN,
    serial STRING,
    thermostats STRING,
    lastMonthBill DOUBLE,
    lastMonthKwh DOUBLE,
    firstDataProcessTime INT,
    plannumber INT,
    utilityunknown STRING,
    utilityName STRING,
    planunknown STRING,
    ratePlanId STRING,
    billCycleCode STRING,
    rateType STRING,
    defaultRate DOUBLE,
    rateQuery STRING,
    masterTariffId STRING,
    emailsBlocked BOOLEAN,
    notificationsBlocked BOOLEAN,
    dailyTierChangeAlertList STRING,
    weeklySummaryList STRING,
    monthlySummaryList STRING,
    disconnectsSentPerWeek STRING,
    dailyTierChangeAlert BOOLEAN,
    dailyUsageUpAlert BOOLEAN,
    dailyUsageDownAlert BOOLEAN,
    dailyPeakToUUsageUpAlert BOOLEAN,
    dailyUsageUpAlertList STRING,
    dailyUsageUpAlertPercent DOUBLE,
    dailyUsageDownAlertList STRING,
    dailyUsageDownAlertPercent DOUBLE,
    dailyPeakToUUsageUpAlertPercent DOUBLE,
    dailyPeakToUUsageUpAlertList STRING,
    notifyEmailStatusChange BOOLEAN,
    notifyEmailState STRING,
    notifyEmailGBState STRING,
    notifyEmailWeeklyStatus BOOLEAN,
    notifyEmailMonthlyStatus BOOLEAN,
    firstTimeHanConnectEmailed BOOLEAN,
    firstTimeGBConnectEmailed BOOLEAN,
    firstTimeGBConnectNotified BOOLEAN,
    blackList STRING,
    releaseList STRING,
    nsp STRING,
    nst STRING,
    checkedDILSO BOOLEAN,
    latitude DOUBLE,
    longitude DOUBLE,
    budgetThresholdAmount DOUBLE,
    s3FileDumpState STRING,
    lastStreamedBillProjection INT,
    businessName STRING,
    userSegment STRING,
    userBusinessType STRING,
    partnerProvidedUserBusinessType STRING,
    userBusinessSubType STRING,
    businessTimings STRING,
    smartBudgetEnabled BOOLEAN,
    businessCode STRING,
    addressMatchingThirdPartyData BOOLEAN,
    billingSchedule STRING,
    status STRING,
    crud_op STRING,
    event_date DATE
)
PARTITIONED BY (pilot_id STRING)
STORED AS PARQUET
LOCATION 's3://bidgely-lakehouse-pocs/experiments/experiment2/hudi/history/'
TBLPROPERTIES (
    'hoodie.datasource.write.keygenerator.class'='org.apache.hudi.keygen.SimpleKeyGenerator',
    'hoodie.datasource.write.recordkey.field'='uuid',
    'hoodie.datasource.write.precombine.field'='last_updated_timestamp'
);


MSCK REPAIR TABLE lakehouse_pocs.hudi_exp2_history;




EXPLAIN ANALYZE SELECT pilot_id, uuid, COUNT(*) AS row_count FROM hudi_exp2_history GROUP BY pilot_id, uuid;


-- hybrid-disagg-electric
CREATE EXTERNAL TABLE lakehouse_pocs.delta_exp4_history (
    uuid STRING,
    bill_start_date DATE,
    lastupdate BIGINT,
    event_date DATE,
    ac STRING,
    ac_fan STRING,
    ac_input DOUBLE,
    ac_output DOUBLE,
    alwayson STRING,
    alwaysoninput DOUBLE,
    alwaysonoutput DOUBLE,
    bill_end_date DATE,
    cablebox STRING,
    central_air_conditioning STRING,
    computer STRING,
    cookinginput DOUBLE,
    cookingoutput DOUBLE,
    countrycode STRING,
    dishwasher STRING,
    dvd STRING,
    electricshower STRING,
    electricvehicle STRING,
    electricvehiclesinput DOUBLE,
    electricvehiclesoutput DOUBLE,
    entertainmentandcomputinginput DOUBLE,
    entertainmentandcomputingoutput DOUBLE,
    freezer STRING,
    fridgecombo STRING,
    gameconsole STRING,
    grill STRING,
    hob STRING,
    iron STRING,
    kettle STRING,
    laundryinput DOUBLE,
    laundryoutput DOUBLE,
    lighting STRING,
    lightinginput DOUBLE,
    lightingoutput DOUBLE,
    microwave STRING,
    numbedrooms INT,
    number_of_vacation_days_actual INT,
    number_of_vacation_days_estimated INT,
    numoccupants INT,
    occupanttype STRING,
    otherinput DOUBLE,
    otheroutput DOUBLE,
    oven STRING,
    ownershiptype STRING,
    poolpump STRING,
    poolsandsaunasinput DOUBLE,
    poolsandsaunasoutput DOUBLE,
    propertyagetype STRING,
    propertytype STRING,
    refrigerationinput DOUBLE,
    refrigerationoutput DOUBLE,
    refrigerator STRING,
    room_air_conditioner STRING,
    sauna STRING,
    solar STRING,
    spaceheatinginput DOUBLE,
    spaceheatingoutput DOUBLE,
    spaceheatingtype STRING,
    tablet STRING,
    toaster STRING,
    totalinput DOUBLE,
    totaloutput DOUBLE,
    tumbledrier STRING,
    tv STRING,
    washingmachine STRING,
    waterheatinginput DOUBLE,
    waterheatingoutput DOUBLE,
    waterheatingtype STRING,
    solarinput DOUBLE,
    operationalloadinput DOUBLE,
    operationalloadoutput DOUBLE,
    operationalload STRING,
    anomalousloadinput DOUBLE,
    anomalousloadoutput DOUBLE,
    anomalousload STRING,
    crud_op STRING,
    bill_start_month DATE,
    update_month DATE
)
PARTITIONED BY (pilot_id STRING)
STORED AS PARQUET
LOCATION 's3://bidgely-lakehouse-pocs/experiments/experiment4/deltalake/history/';




MSCK REPAIR TABLE lakehouse_pocs.delta_exp4_history;


-- for hudi hybrid-disagg-electric

CREATE EXTERNAL TABLE lakehouse_pocs.hudi_exp4_history (
    uuid STRING,
    bill_start_date DATE,
    lastupdate BIGINT,
    event_date DATE,
    ac STRING,
    ac_fan STRING,
    ac_input DOUBLE,
    ac_output DOUBLE,
    alwayson STRING,
    alwaysoninput DOUBLE,
    alwaysonoutput DOUBLE,
    bill_end_date DATE,
    cablebox STRING,
    central_air_conditioning STRING,
    computer STRING,
    cookinginput DOUBLE,
    cookingoutput DOUBLE,
    countrycode STRING,
    dishwasher STRING,
    dvd STRING,
    electricshower STRING,
    electricvehicle STRING,
    electricvehiclesinput DOUBLE,
    electricvehiclesoutput DOUBLE,
    entertainmentandcomputinginput DOUBLE,
    entertainmentandcomputingoutput DOUBLE,
    freezer STRING,
    fridgecombo STRING,
    gameconsole STRING,
    grill STRING,
    hob STRING,
    iron STRING,
    kettle STRING,
    laundryinput DOUBLE,
    laundryoutput DOUBLE,
    lighting STRING,
    lightinginput DOUBLE,
    lightingoutput DOUBLE,
    microwave STRING,
    numbedrooms INT,
    number_of_vacation_days_actual INT,
    number_of_vacation_days_estimated INT,
    numoccupants INT,
    occupanttype STRING,
    otherinput DOUBLE,
    otheroutput DOUBLE,
    oven STRING,
    ownershiptype STRING,
    poolpump STRING,
    poolsandsaunasinput DOUBLE,
    poolsandsaunasoutput DOUBLE,
    propertyagetype STRING,
    propertytype STRING,
    refrigerationinput DOUBLE,
    refrigerationoutput DOUBLE,
    refrigerator STRING,
    room_air_conditioner STRING,
    sauna STRING,
    solar STRING,
    spaceheatinginput DOUBLE,
    spaceheatingoutput DOUBLE,
    spaceheatingtype STRING,
    tablet STRING,
    toaster STRING,
    totalinput DOUBLE,
    totaloutput DOUBLE,
    tumbledrier STRING,
    tv STRING,
    washingmachine STRING,
    waterheatinginput DOUBLE,
    waterheatingoutput DOUBLE,
    waterheatingtype STRING,
    solarinput DOUBLE,
    operationalloadinput DOUBLE,
    operationalloadoutput DOUBLE,
    operationalload STRING,
    anomalousloadinput DOUBLE,
    anomalousloadoutput DOUBLE,
    anomalousload STRING,
    crud_op STRING,
    bill_start_month DATE,
    update_month DATE
)
PARTITIONED BY (pilot_id STRING)
STORED AS PARQUET
LOCATION 's3://bidgely-lakehouse-pocs/experiments/experiment4_1/hudi/history/'
TBLPROPERTIES (
    'hoodie.datasource.write.keygenerator.class'='org.apache.hudi.keygen.SimpleKeyGenerator',
    'hoodie.datasource.write.recordkey.field'='uuid',
    'hoodie.datasource.write.precombine.field'='lastupdate'
);


MSCK REPAIR TABLE lakehouse_pocs.hudi_exp4_history;






--

CREATE EXTERNAL TABLE lakehouse_pocs.delta_exp5_history (
    uuid STRING,
    hid INT,
    billing_start_time TIMESTAMP,
    lastupdate BIGINT,
    event_date DATE,
    billing_end_time TIMESTAMP,
    consumption_value DOUBLE,
    cost DOUBLE,
    billcycle_fixed_cost DOUBLE,
    bidgely_generated_invoice BOOLEAN,
    invoice_code STRING,
    user_type STRING,
    solar BOOLEAN,
    data_update_mode INT,
    data_update_timestamp TIMESTAMP,
    measurement_type STRING,
    transition_bill_cycle BOOLEAN,
    invoice_ingested_timestamp BIGINT,
    bill_start_month DATE,
    update_month DATE
)
PARTITIONED BY (pilot_id STRING)
STORED AS PARQUET
LOCATION 's3://bidgely-lakehouse-pocs/experiments/experiment5/deltalake/history/';


MSCK REPAIR TABLE lakehouse_pocs.delta_exp5_history;







CREATE EXTERNAL TABLE lakehouse_pocs.hudi_exp5_history (
    uuid STRING,
    hid INT,
    billing_start_time TIMESTAMP,
    lastupdate BIGINT,
    event_date DATE,
    billing_end_time TIMESTAMP,
    consumption_value DOUBLE,
    cost DOUBLE,
    billcycle_fixed_cost DOUBLE,
    bidgely_generated_invoice BOOLEAN,
    invoice_code STRING,
    user_type STRING,
    solar BOOLEAN,
    data_update_mode INT,
    data_update_timestamp TIMESTAMP,
    measurement_type STRING,
    transition_bill_cycle BOOLEAN,
    invoice_ingested_timestamp BIGINT,
    bill_start_month DATE,
    update_month DATE
)
PARTITIONED BY (pilot_id STRING)
STORED AS PARQUET
LOCATION 's3://bidgely-lakehouse-pocs/experiments/experiment5_1/hudi/history/'
TBLPROPERTIES (
    'hoodie.datasource.write.keygenerator.class'='org.apache.hudi.keygen.SimpleKeyGenerator',
    'hoodie.datasource.write.recordkey.field'='uuid',
    'hoodie.datasource.write.precombine.field'='lastupdate'
);



MSCK REPAIR TABLE lakehouse_pocs.hudi_exp5_history;